// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using aspnet_react.Data;

#nullable disable

namespace aspnet_react.Migrations
{
    [DbContext(typeof(AppDBContext))]
    partial class AppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("aspnet_react.Data.Post", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(100000)
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("PostId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            PostId = 1,
                            Content = "this is post 1 and it has a great content",
                            Title = "Post1"
                        },
                        new
                        {
                            PostId = 2,
                            Content = "this is post 2 and it has a great content",
                            Title = "Post2"
                        },
                        new
                        {
                            PostId = 3,
                            Content = "this is post 3 and it has a great content",
                            Title = "Post3"
                        },
                        new
                        {
                            PostId = 4,
                            Content = "this is post 4 and it has a great content",
                            Title = "Post4"
                        },
                        new
                        {
                            PostId = 5,
                            Content = "this is post 5 and it has a great content",
                            Title = "Post5"
                        },
                        new
                        {
                            PostId = 6,
                            Content = "this is post 6 and it has a great content",
                            Title = "Post6"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
